language: scala
sudo: false
jdk: openjdk8
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
script:
  - sbt ";set g8Properties in g8 in Test ~= { _ + (\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\")}; g8Test"
