name: scala-steward
on:
  push:
    branches: [ master ]
  schedule:
  - cron: '0 21 * * *'
jobs:
  scala-steward:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Generate token
      id: generate_token
      if: ${{ !github.event.repository.fork }}
      uses: tibdex/github-app-token@v1
      with:
        app_id: 89698
        private_key: ${{ secrets.UNFILTERED_APP_KEY }}
    - name: Launch Scala Steward
      if: ${{ !github.event.repository.fork }}
      uses: scala-steward-org/scala-steward-action@v2.13.6
      with:
        github-token: ${{ steps.generate_token.outputs.token }}
        author-email: "74865306+unfiltered-app[bot]@users.noreply.github.com"
        author-name: "unfiltered-app[bot]"
